### ISSUE TITLE
Need More Collaborators

### ISSUE THREAD

**Issue by samuraininja360** [meower-media-co/Gamr-Website#1]
Hello Explosion, 
You may recognize my username but I am a scratch programmer willing to join your HTML/CSS/JS Collab. I have experience in JavaScript Game Development and DOM. I am a front-end web developer but I will start learning node.js soon. If you need any collaborators I am ready to join.

**Comment by Explosion-Scratch** [comment]
Hi! I'm just helping with some random stuff. You should as DabDatBass (on scratch)

**Comment by samuraininja360** [comment]
What is DabDatBass? Dab Data Base

**Comment by Explosion-Scratch** [comment]
A user on scratch lol

**Comment by Explosion-Scratch** [comment]
https://scratch.mit.edu/users/DabDatBass
